# Generated by Django 4.0.4 on 2022-09-20 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invName', models.CharField(max_length=20)),
                ('invCreateDate', models.DateField(auto_now=True)),
                ('sharedTo', models.ManyToManyField(default=None, null=True, related_name='shared', to=settings.AUTH_USER_MODEL)),
                ('user_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdName', models.CharField(max_length=80)),
                ('freezerPrd', models.BooleanField(default=False)),
                ('readyToEat', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('edible', 'Edible'), ('non-edible', 'Non-Edible')], default='edible', max_length=10)),
                ('product_weight_category', models.CharField(choices=[('kilogram', 'Kilogram'), ('gram', 'Gram'), ('litre', 'Litre'), ('ml', 'Mili Litre'), ('pieces', 'Pieces')], default='kilogram', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('prdPrice', models.FloatField()),
                ('prdAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryAPI.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdQty', models.IntegerField()),
                ('product_weight_per_quantity', models.IntegerField(default=0)),
                ('totalquantity', models.IntegerField(default=0)),
                ('invAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryAPI.inventory')),
                ('prodAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryAPI.product')),
            ],
        ),
    ]
