# Generated by Django 4.0.4 on 2022-09-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPI', '0002_alter_inventory_sharedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
