# Generated by Django 4.0.4 on 2022-10-14 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventoryAPI', '0003_alter_productpricehistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transDate', models.DateField(auto_now=True)),
                ('totalAmount', models.FloatField()),
                ('totalItem', models.IntegerField()),
                ('invAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryAPI.inventory')),
                ('marketAssocaited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactionAPI.market')),
                ('user_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdQty', models.IntegerField()),
                ('prdPerPrice', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('prdAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryAPI.product')),
                ('transactionAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactionAPI.transactionrecord')),
            ],
        ),
    ]
